#!/bin/bash

usage() {
cat <<EOF
================================================================================
setup
================================================================================
Purpose: Sets up the conda and renv environments for the scripts to run.
Also deletes possible unwanted SLURM directives.
Author: Sam Fletcher
Contact: s.o.fletcher@exeter.ac.uk
Dependencies: conda
================================================================================
EOF
    exit 0
}

if [ "$#" -eq 0 ]; then usage; fi 

config_file_location=$1
source "${config_file_location}" || { echo "could not find config file at:
${config_file_location}"; exit 1; }

## =========================== ##
##   REMOVE SLURM DIRECITVES   ##
## =========================== ##

script_list=$(find "${REPO_DIR}" -type f -name "*.sh")

echo "Do you want to remove SLURM directives associated with UoE's HPC?"
echo "(y/n)"
read -r delete_slurm_directives

if [[ "${delete_slurm_directives}" == "y" ]]; then
    for file in $script_list; do
        sed -i "s/#SBATCH -A Research_Project-MRC190311//g" "${file}"
        sed -i "s/#SBATCH -p mrcq//g" "${file}"
    done
fi

## ===================== ##
##   CONDA ENVIRONMENT   ##
## ===================== ##

source "${CONDA_SHELL}" || { echo "Could not find conda shell at:
${CONDA_SHELL}"; exit 1; }
conda config --add channels bioconda
conda config --add channels conda-forge
conda config --add channels anaconda

conda create --name ChromBinarize --file "${REPO_DIR}/requirements.txt"

conda activate ChromBinarize

## ==================== ##
##   RENV ENVIRONMENT   ##
## ==================== ##

Rscript -e "install.packages('renv', repo='https://cloud.r-project.org')"

cd "${REPO_DIR}" || exit 1
Rscript -e "renv::restore(); library(fitdistrplus); print('success')"
