name: test-chrombinarize

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        working-directory: chrombinarize

      - name: Run tests
        run: |
          library(testthat)
          library(chrombinarize)
          test_dir("tests/testthat")
        working-directory: chrombinarize
