name: test-chrombinarize

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        uses: r-lib/actions/setup-renv@v2

      - name: Run tests
        run: |
          library(testthat)
          library(chrombinarize)
          test_dir("chrombinarize/tests/testthat")
        shell: Rscript {0}
